apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: manneyvictor/projeto-database:1.0
          args:
            - "--ignore-db-dir=lost+found"
          imagePullPolicy: Always
          name: mysql
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3306
              name: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: manneyvictor/projeto-backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
