apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: NodePort
  selector:
    app: php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-connection
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
